# Scaffolding generated by Casein v5.1.1.5

module Casein
  class OffersController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Offers'
  		@offers = Offer.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View offer'
      @offer = Offer.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new offer'
    	@offer = Offer.new
    end

    def create
      @offer = Offer.new offer_params
    
      if @offer.save
        flash[:notice] = 'Offer created'
        redirect_to casein_offers_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new offer'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update offer'
      
      @offer = Offer.find params[:id]
    
      if @offer.update_attributes offer_params
        flash[:notice] = 'Offer has been updated'
        redirect_to casein_offers_path
      else
        flash.now[:warning] = 'There were problems when trying to update this offer'
        render :action => :show
      end
    end
 
    def destroy
      @offer = Offer.find params[:id]

      @offer.destroy
      flash[:notice] = 'Offer has been deleted'
      redirect_to casein_offers_path
    end
  
    private
      
      def offer_params
        params.require(:offer).permit(:title, :content, :image)
      end

  end
end